import { faGoogle } from '@fortawesome/free-brands-svg-icons';
import { 
    faEye, 
    faEyeSlash, 
    faCow, 
    faEarthEurope, 
    faHeart, 
    faKitMedical,
    faCirclePlus,
    faTrash,
    faUser,
    faTriangleExclamation,
    faMagnifyingGlass,
    faArrowRight,
    faVenus,
    faMars,
    faPlus,
    faBookmark,
    faDownload,
    faUpload,
} from '@fortawesome/free-solid-svg-icons';

export default {
    faGoogle,
    faEye,
    faEyeSlash,
    faCow,
    faEarthEurope,
    faHeart,
    faKitMedical,
    faCirclePlus,
    faTrash,
    faUser,
    faTriangleExclamation,
    faMagnifyingGlass,
    faArrowRight,
    faVenus,
    faMars,
    faPlus,
    faBookmark,
    faDownload,
    faUpload,
};